[2023-07-16 10:24:03,607: INFO: main:  stage Data Ingestion stage started ]
[2023-07-16 10:24:03,608: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-07-16 10:24:03,608: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-16 10:24:03,608: INFO: common: created directory at: artifacts]
[2023-07-16 10:24:03,609: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 11, in main
    data_ingestion_config = config.get_data_ingestion_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2023-07-16 10:25:34,958: INFO: main:  stage Data Ingestion stage started ]
[2023-07-16 10:25:34,959: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-07-16 10:25:34,959: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-16 10:25:34,959: INFO: common: created directory at: artifacts]
[2023-07-16 10:25:34,959: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-16 10:25:34,961: ERROR: main: unknown url type: '../samsumdata.zip']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 13, in main
    data_ingestion.download_file()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/components/data_ingestion.py", line 17, in download_file
    filename, headers = request.urlretrieve(
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '../samsumdata.zip'
[2023-07-16 10:28:10,778: INFO: main:  stage Data Ingestion stage started ]
[2023-07-16 10:28:10,779: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-07-16 10:28:10,779: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-16 10:28:10,779: INFO: common: created directory at: artifacts]
[2023-07-16 10:28:10,779: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-16 10:28:10,781: ERROR: main: unknown url type: './samsumdata.zip']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 13, in main
    data_ingestion.download_file()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/components/data_ingestion.py", line 17, in download_file
    filename, headers = request.urlretrieve(
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: './samsumdata.zip'
[2023-07-16 10:36:58,576: INFO: main:  stage Data Ingestion stage started ]
[2023-07-16 10:36:58,577: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-07-16 10:36:58,577: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-16 10:36:58,577: INFO: common: created directory at: artifacts]
[2023-07-16 10:36:58,577: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-16 10:36:58,580: ERROR: main: unknown url type: './samsumdata.zip']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 13, in main
    data_ingestion.download_file()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/components/data_ingestion.py", line 17, in download_file
    filename, headers = request.urlretrieve(
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: './samsumdata.zip'
[2023-07-16 10:37:46,766: INFO: main:  stage Data Ingestion stage started ]
[2023-07-16 10:37:46,767: ERROR: main: mapping values are not allowed here
  in "config/config.yaml", line 8, column 25]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 10, in main
    config = ConfigurationManager()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/config/configuration.py", line 11, in __init__
    self.config = read_yaml(config_filepath) #filepath from constants folder
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/utils/common.py", line 21, in read_yaml
    raise e
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/utils/common.py", line 15, in read_yaml
    content = yaml.safe_load(yaml_file)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config/config.yaml", line 8, column 25
[2023-07-16 10:38:00,488: INFO: main:  stage Data Ingestion stage started ]
[2023-07-16 10:38:00,489: ERROR: main: mapping values are not allowed here
  in "config/config.yaml", line 8, column 25]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/pipeline/stage_01_data_ingestion.py", line 10, in main
    config = ConfigurationManager()
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/config/configuration.py", line 11, in __init__
    self.config = read_yaml(config_filepath) #filepath from constants folder
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/utils/common.py", line 21, in read_yaml
    raise e
  File "/Users/tanveersingh/Desktop/text-summarizer/src/textSummarizer/utils/common.py", line 15, in read_yaml
    content = yaml.safe_load(yaml_file)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/Users/tanveersingh/miniconda3/envs/text-s/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config/config.yaml", line 8, column 25
[2023-07-16 10:39:27,460: INFO: main:  stage Data Ingestion stage started ]
[2023-07-16 10:39:27,461: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-07-16 10:39:27,461: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-16 10:39:27,461: INFO: common: created directory at: artifacts]
[2023-07-16 10:39:27,461: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-16 10:39:29,134: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4B98:0F3F:10CF2E:13F81A:64B3585F
Accept-Ranges: bytes
Date: Sun, 16 Jul 2023 02:39:28 GMT
Via: 1.1 varnish
X-Served-By: cache-qpg1254-QPG
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1689475168.075800,VS0,VE708
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: fc9c36fa7299ab86883945af0f2049a38720a35a
Expires: Sun, 16 Jul 2023 02:44:28 GMT
Source-Age: 0

]
[2023-07-16 10:39:29,229: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
